image:
  file: .gitpod.Dockerfile
tasks:
  - name: Get additional dependencies
    command: |
      sudo apt update
      echo "Installing xdg-user-dirs to be able to locate directories"
      sudo apt install -y xdg-user-dirs

  - name: Build for different targets
    init: |
      if test ! -e "pubspec.yaml"; then {
        rm -f /workspace/.template_init
        flutter create --project-name gitpod_flutter_quickstart .
      } fi

      ### If you want to build for android, consider uncommenting the below lines
      # flutter build -v bundle
      # flutter build -v appbundle
      flutter build -v apk

      ### This line is necessary for the below `- name: Run project` to await before proceeding to `flutter run` when prebuilds are not effective
      # We could use `gp sync-[done|await] <id>` but that won't work between `init` and `command`
      touch /workspace/.template_init

  - name: Prepare project
    command: |
      printf "\033[3J\033c\033[3J" && if test ! -e /workspace/.template_init; then {
        printf 'info[gitpod]: %s\n' "Waiting for the flutter build process to complete ..."
        until test -e /workspace/.template_init; do
          sleep 0.5
        done
      } fi
      flutter pub get
      # flutter run

ports:
  - port: 5900
    onOpen: ignore
  # vnc
  - port: 6080
    onOpen: open-preview
  # flutter
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
