workflows:
  default-workflow:
    name: Internal Test Release
    max_build_duration: 30
    environment:
      groups:
        - google_play
        - keystore_credentials
        - github
      flutter: stable
      vars:
        PACKAGE_NAME: "app.schildpad.schildpad"
        GOOGLE_PLAY_TRACK: internal
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Analyze code
        script: |
          flutter analyze
      - name: Verify formatting
        script: |
          dart format --output=none --set-exit-if-changed .
      - name: Unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Build AAB with Flutter for Play store
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release --build-number=$BUILD_NUMBER
      - name: Build universal apk for other stores and GitHub
        ignore_failure: true
        script: |
          flutter build apk --release
          
          mv \
            build/app/outputs/flutter-apk/app-release.apk \
            build/app/outputs/flutter-apk/schildpad-${CM_TAG}-universal.apk
            
      - name: Build apks per abi for other stores and GitHub
        ignore_failure: true
        script: |
          flutter build apk --release --split-per-abi
          
          mv \
              build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
              build/app/outputs/flutter-apk/schildpad-${CM_TAG}-arm64.apk
          mv \
              build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
              build/app/outputs/flutter-apk/schildpad-${CM_TAG}-arm.apk
          mv \
              build/app/outputs/flutter-apk/app-x86_64-release.apk \
              build/app/outputs/flutter-apk/schildpad-${CM_TAG}-x64.apk          

    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - codemagic@schildpad.app
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      scripts:
        - name: Publish to GitHub
          ignore_failure: true
          script: |
            #!/usr/bin/env zsh
            
            # Publish only for tag builds
            if [ -z ${CM_TAG} ]; then
              echo "Not a tag build, will not publish GitHub release"
              exit 0
            fi
            
            gh release create "${CM_TAG}" \
              $CM_BUILD_OUTPUT_DIR/schildpad-${CM_TAG}-universal.apk \
              $CM_BUILD_OUTPUT_DIR/schildpad-${CM_TAG}-arm64.apk \
              $CM_BUILD_OUTPUT_DIR/schildpad-${CM_TAG}-arm.apk \
              $CM_BUILD_OUTPUT_DIR/schildpad-${CM_TAG}-x64.apk \
              --draft \
              --title "Schildpad Launcher ${CM_TAG}"
