workflows:
  default-workflow:
    name: Internal Test Release
    max_build_duration: 30
    environment:
      groups:
        - google_play
        - keystore_credentials
        - github
      flutter: stable
      vars:
        PACKAGE_NAME: "app.schildpad.schildpad"
        GOOGLE_PLAY_TRACK: internal
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release --build-number=$BUILD_NUMBER
      - name: Build universal apk
        script: |
          android-app-bundle build-universal-apk \
            --bundle 'build/**/outputs/**/*.aab' \
            --ks $CM_KEYSTORE_PATH \
            --ks-pass $CM_KEYSTORE_PASSWORD \
            --ks-key-alias $CM_KEY_ALIAS \
            --key-pass $CM_KEY_PASSWORD
          
          mv \
            build/app/outputs/bundle/release/app-release-universal.apk \
            build/app/outputs/bundle/release/schildpad-${CM_TAG}.apk
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - codemagic@schildpad.app
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      scripts:
        - name: Publish to GitHub
          script: |
            #!/usr/bin/env zsh
            
            # Publish only for tag builds
            if [ -z ${CM_TAG} ]; then
              echo "Not a tag build, will not publish GitHub release"
              exit 0
            fi
            
            gh release create "${CM_TAG}" \
              --draft \
              --title "Schildpad Launcher ${CM_TAG}" \              
              build/app/outputs/bundle/release/schildpad-${CM_TAG}.apk