name: schildpad
description: Schildpad is a launcher app for Android built with Flutter. It aims to be robust but beautiful, just like a turtle.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  go_router: ^6.4.0
  flutter_riverpod: ^2.0.2
  equatable: ^2.0.3
  android_intent_plus: ^3.1.1
  backdrop: ^0.8.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  package_info_plus: ^3.0.1
  url_launcher: ^6.1.6
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  toggle_switch:
    git:
      url: https://github.com/joelpaulkoch/toggle_switch

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  build_runner: any
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/schildpad_logo.svg
