name: schildpad
description: Schildpad is a launcher app for Android built with Flutter. It aims to be robust but beautiful, just like a turtle.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.0

isar_version: &isar_version 3.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  go_router: ^4.4.1
  flutter_riverpod: ^2.0.2
  equatable: ^2.0.3
  android_intent_plus: ^3.1.1
  backdrop: ^0.8.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.6
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/schildpad_logo.svg
