name: schildpad
description: Schildpad is a launcher app for Android built with Flutter. It aims to be robust but beautiful, just like a turtle.

publish_to: "none"

version: 1.2.10+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  go_router: ^7.0.0
  flutter_riverpod: ^2.0.2
  equatable: ^2.0.3
  android_intent_plus: ^4.0.0
  backdrop: ^0.9.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  package_info_plus: ^4.0.0
  url_launcher: ^6.1.6
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  toggle_switch: ^2.1.0
  path_provider: ^2.0.15

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  build_runner: any
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/schildpad_logo.svg
