//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: lib/installed_app_widgets/proto/installed_app_widgets.proto

package app.schildpad.schildpad.protos;

@kotlin.jvm.JvmName("-initializeinstalledAppWidgets")
inline fun installedAppWidgets(block: app.schildpad.schildpad.protos.InstalledAppWidgetsKt.Dsl.() -> kotlin.Unit): app.schildpad.schildpad.protos.InstalledAppWidgets =
  app.schildpad.schildpad.protos.InstalledAppWidgetsKt.Dsl._create(app.schildpad.schildpad.protos.InstalledAppWidgets.newBuilder())
      .apply { block() }._build()
object InstalledAppWidgetsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: app.schildpad.schildpad.protos.InstalledAppWidgets.Builder
  ) {
      companion object {
          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _create(builder: app.schildpad.schildpad.protos.InstalledAppWidgets.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): app.schildpad.schildpad.protos.InstalledAppWidgets = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      class AppWidgetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       */
      val appWidgets: com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>
          @kotlin.jvm.JvmSynthetic
          get() = com.google.protobuf.kotlin.DslList(
              _builder.getAppWidgetsList()
          )

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       * @param value The appWidgets to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAppWidgets")
      fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.add(value: app.schildpad.schildpad.protos.AppWidget) {
          _builder.addAppWidgets(value)
      }

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       * @param value The appWidgets to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAppWidgets")
      @Suppress("NOTHING_TO_INLINE")
      inline operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.plusAssign(
          value: app.schildpad.schildpad.protos.AppWidget
      ) {
          add(value)
      }

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       * @param values The appWidgets to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllAppWidgets")
      fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.addAll(values: kotlin.collections.Iterable<app.schildpad.schildpad.protos.AppWidget>) {
          _builder.addAllAppWidgets(values)
      }

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       * @param values The appWidgets to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllAppWidgets")
      @Suppress("NOTHING_TO_INLINE")
      inline operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.plusAssign(
          values: kotlin.collections.Iterable<app.schildpad.schildpad.protos.AppWidget>
      ) {
          addAll(values)
      }

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       * @param index The index to set the value at.
       * @param value The appWidgets to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setAppWidgets")
      operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.set(
          index: kotlin.Int,
          value: app.schildpad.schildpad.protos.AppWidget
      ) {
          _builder.setAppWidgets(index, value)
      }

      /**
       * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearAppWidgets")
      fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.AppWidget, AppWidgetsProxy>.clear() {
          _builder.clearAppWidgets()
      }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun app.schildpad.schildpad.protos.InstalledAppWidgets.copy(block: app.schildpad.schildpad.protos.InstalledAppWidgetsKt.Dsl.() -> kotlin.Unit): app.schildpad.schildpad.protos.InstalledAppWidgets =
  app.schildpad.schildpad.protos.InstalledAppWidgetsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

