//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: lib/installed_apps/proto/installed_apps.proto

package app.schildpad.schildpad.protos;

@kotlin.jvm.JvmName("-initializeinstalledApps")
inline fun installedApps(block: app.schildpad.schildpad.protos.InstalledAppsKt.Dsl.() -> kotlin.Unit): app.schildpad.schildpad.protos.InstalledApps =
    app.schildpad.schildpad.protos.InstalledAppsKt.Dsl._create(app.schildpad.schildpad.protos.InstalledApps.newBuilder())
        .apply { block() }._build()
object InstalledAppsKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
        private val _builder: app.schildpad.schildpad.protos.InstalledApps.Builder
    ) {
        companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: app.schildpad.schildpad.protos.InstalledApps.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): app.schildpad.schildpad.protos.InstalledApps = _builder.build()

        /**
         * An uninstantiable, behaviorless type to represent the field in
         * generics.
         */
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        class AppsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        val apps: com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>
            @kotlin.jvm.JvmSynthetic
            get() = com.google.protobuf.kotlin.DslList(
                _builder.getAppsList()
            )

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         * @param value The apps to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addApps")
        fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.add(value: app.schildpad.schildpad.protos.App) {
            _builder.addApps(value)
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         * @param value The apps to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignApps")
        @Suppress("NOTHING_TO_INLINE")
        inline operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.plusAssign(
            value: app.schildpad.schildpad.protos.App
        ) {
            add(value)
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         * @param values The apps to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addAllApps")
        fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.addAll(values: kotlin.collections.Iterable<app.schildpad.schildpad.protos.App>) {
            _builder.addAllApps(values)
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         * @param values The apps to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignAllApps")
        @Suppress("NOTHING_TO_INLINE")
        inline operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.plusAssign(
            values: kotlin.collections.Iterable<app.schildpad.schildpad.protos.App>
        ) {
            addAll(values)
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         * @param index The index to set the value at.
         * @param value The apps to set.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("setApps")
        operator fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.set(
            index: kotlin.Int,
            value: app.schildpad.schildpad.protos.App
        ) {
            _builder.setApps(index, value)
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("clearApps")
        fun com.google.protobuf.kotlin.DslList<app.schildpad.schildpad.protos.App, AppsProxy>.clear() {
            _builder.clearApps()
        }

    }
}
@kotlin.jvm.JvmSynthetic
inline fun app.schildpad.schildpad.protos.InstalledApps.copy(block: app.schildpad.schildpad.protos.InstalledAppsKt.Dsl.() -> kotlin.Unit): app.schildpad.schildpad.protos.InstalledApps =
    app.schildpad.schildpad.protos.InstalledAppsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

