// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_apps/proto/installed_apps.proto

package app.schildpad.schildpad.protos;

/**
 * Protobuf type {@code schildpad.App}
 */
public final class App extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:schildpad.App)
        AppOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use App.newBuilder() to construct.
  private App(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private App() {
    name_ = "";
    packageName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new App();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private App(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 26: {
            app.schildpad.schildpad.protos.App.DrawableData.Builder subBuilder = null;
            if (icon_ != null) {
              subBuilder = icon_.toBuilder();
            }
            icon_ = input.readMessage(app.schildpad.schildpad.protos.App.DrawableData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(icon_);
              icon_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    app.schildpad.schildpad.protos.App.class, app.schildpad.schildpad.protos.App.Builder.class);
  }

  public interface DrawableDataOrBuilder extends
          // @@protoc_insertion_point(interface_extends:schildpad.App.DrawableData)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     *
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }

  /**
   * Protobuf type {@code schildpad.App.DrawableData}
   */
  public static final class DrawableData extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:schildpad.App.DrawableData)
          DrawableDataOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use DrawableData.newBuilder() to construct.
    private DrawableData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private DrawableData() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new DrawableData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private DrawableData(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_DrawableData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_DrawableData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      app.schildpad.schildpad.protos.App.DrawableData.class, app.schildpad.schildpad.protos.App.DrawableData.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;

    /**
     * <code>bytes data = 1;</code>
     *
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof app.schildpad.schildpad.protos.App.DrawableData)) {
        return super.equals(obj);
      }
      app.schildpad.schildpad.protos.App.DrawableData other = (app.schildpad.schildpad.protos.App.DrawableData) obj;

      if (!getData()
              .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.App.DrawableData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(app.schildpad.schildpad.protos.App.DrawableData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code schildpad.App.DrawableData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:schildpad.App.DrawableData)
            app.schildpad.schildpad.protos.App.DrawableDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_DrawableData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_DrawableData_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        app.schildpad.schildpad.protos.App.DrawableData.class, app.schildpad.schildpad.protos.App.DrawableData.Builder.class);
      }

      // Construct using app.schildpad.schildpad.protos.App.DrawableData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_DrawableData_descriptor;
      }

      @java.lang.Override
      public app.schildpad.schildpad.protos.App.DrawableData getDefaultInstanceForType() {
        return app.schildpad.schildpad.protos.App.DrawableData.getDefaultInstance();
      }

      @java.lang.Override
      public app.schildpad.schildpad.protos.App.DrawableData build() {
        app.schildpad.schildpad.protos.App.DrawableData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public app.schildpad.schildpad.protos.App.DrawableData buildPartial() {
        app.schildpad.schildpad.protos.App.DrawableData result = new app.schildpad.schildpad.protos.App.DrawableData(this);
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.schildpad.schildpad.protos.App.DrawableData) {
          return mergeFrom((app.schildpad.schildpad.protos.App.DrawableData) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.schildpad.schildpad.protos.App.DrawableData other) {
        if (other == app.schildpad.schildpad.protos.App.DrawableData.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        app.schildpad.schildpad.protos.App.DrawableData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.schildpad.schildpad.protos.App.DrawableData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>bytes data = 1;</code>
       *
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      /**
       * <code>bytes data = 1;</code>
       *
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes data = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearData() {

        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:schildpad.App.DrawableData)
    }

    // @@protoc_insertion_point(class_scope:schildpad.App.DrawableData)
    private static final app.schildpad.schildpad.protos.App.DrawableData DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new app.schildpad.schildpad.protos.App.DrawableData();
    }

    public static app.schildpad.schildpad.protos.App.DrawableData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DrawableData>
            PARSER = new com.google.protobuf.AbstractParser<DrawableData>() {
      @java.lang.Override
      public DrawableData parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new DrawableData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DrawableData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DrawableData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.App.DrawableData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;

  /**
   * <code>string name = 1;</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }

  /**
   * <code>string name = 1;</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object packageName_;

  /**
   * <code>string packageName = 2;</code>
   *
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }

  /**
   * <code>string packageName = 2;</code>
   *
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICON_FIELD_NUMBER = 3;
  private app.schildpad.schildpad.protos.App.DrawableData icon_;

  /**
   * <code>.schildpad.App.DrawableData icon = 3;</code>
   *
   * @return Whether the icon field is set.
   */
  @java.lang.Override
  public boolean hasIcon() {
    return icon_ != null;
  }

  /**
   * <code>.schildpad.App.DrawableData icon = 3;</code>
   *
   * @return The icon.
   */
  @java.lang.Override
  public app.schildpad.schildpad.protos.App.DrawableData getIcon() {
    return icon_ == null ? app.schildpad.schildpad.protos.App.DrawableData.getDefaultInstance() : icon_;
  }

  /**
   * <code>.schildpad.App.DrawableData icon = 3;</code>
   */
  @java.lang.Override
  public app.schildpad.schildpad.protos.App.DrawableDataOrBuilder getIconOrBuilder() {
    return getIcon();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageName_);
    }
    if (icon_ != null) {
      output.writeMessage(3, getIcon());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, packageName_);
    }
    if (icon_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(3, getIcon());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof app.schildpad.schildpad.protos.App)) {
      return super.equals(obj);
    }
    app.schildpad.schildpad.protos.App other = (app.schildpad.schildpad.protos.App) obj;

    if (!getName()
            .equals(other.getName())) return false;
    if (!getPackageName()
            .equals(other.getPackageName())) return false;
    if (hasIcon() != other.hasIcon()) return false;
    if (hasIcon()) {
      if (!getIcon()
              .equals(other.getIcon())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    if (hasIcon()) {
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static app.schildpad.schildpad.protos.App parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static app.schildpad.schildpad.protos.App parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static app.schildpad.schildpad.protos.App parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(app.schildpad.schildpad.protos.App prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code schildpad.App}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:schildpad.App)
          app.schildpad.schildpad.protos.AppOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      app.schildpad.schildpad.protos.App.class, app.schildpad.schildpad.protos.App.Builder.class);
    }

    // Construct using app.schildpad.schildpad.protos.App.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      packageName_ = "";

      if (iconBuilder_ == null) {
        icon_ = null;
      } else {
        icon_ = null;
        iconBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_App_descriptor;
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.App getDefaultInstanceForType() {
      return app.schildpad.schildpad.protos.App.getDefaultInstance();
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.App build() {
      app.schildpad.schildpad.protos.App result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.App buildPartial() {
      app.schildpad.schildpad.protos.App result = new app.schildpad.schildpad.protos.App(this);
      result.name_ = name_;
      result.packageName_ = packageName_;
      if (iconBuilder_ == null) {
        result.icon_ = icon_;
      } else {
        result.icon_ = iconBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof app.schildpad.schildpad.protos.App) {
        return mergeFrom((app.schildpad.schildpad.protos.App) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(app.schildpad.schildpad.protos.App other) {
      if (other == app.schildpad.schildpad.protos.App.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      if (other.hasIcon()) {
        mergeIcon(other.getIcon());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      app.schildpad.schildpad.protos.App parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (app.schildpad.schildpad.protos.App) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      name_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {

      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }

    /**
     * <code>string name = 1;</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";

    /**
     * <code>string packageName = 2;</code>
     *
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string packageName = 2;</code>
     *
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
    getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string packageName = 2;</code>
     *
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      packageName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string packageName = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {

      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }

    /**
     * <code>string packageName = 2;</code>
     *
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      packageName_ = value;
      onChanged();
      return this;
    }

    private app.schildpad.schildpad.protos.App.DrawableData icon_;
    private com.google.protobuf.SingleFieldBuilderV3<
            app.schildpad.schildpad.protos.App.DrawableData, app.schildpad.schildpad.protos.App.DrawableData.Builder, app.schildpad.schildpad.protos.App.DrawableDataOrBuilder> iconBuilder_;

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     *
     * @return Whether the icon field is set.
     */
    public boolean hasIcon() {
      return iconBuilder_ != null || icon_ != null;
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     *
     * @return The icon.
     */
    public app.schildpad.schildpad.protos.App.DrawableData getIcon() {
      if (iconBuilder_ == null) {
        return icon_ == null ? app.schildpad.schildpad.protos.App.DrawableData.getDefaultInstance() : icon_;
      } else {
        return iconBuilder_.getMessage();
      }
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public Builder setIcon(app.schildpad.schildpad.protos.App.DrawableData value) {
      if (iconBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        icon_ = value;
        onChanged();
      } else {
        iconBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public Builder setIcon(
            app.schildpad.schildpad.protos.App.DrawableData.Builder builderForValue) {
      if (iconBuilder_ == null) {
        icon_ = builderForValue.build();
        onChanged();
      } else {
        iconBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public Builder mergeIcon(app.schildpad.schildpad.protos.App.DrawableData value) {
      if (iconBuilder_ == null) {
        if (icon_ != null) {
          icon_ =
                  app.schildpad.schildpad.protos.App.DrawableData.newBuilder(icon_).mergeFrom(value).buildPartial();
        } else {
          icon_ = value;
        }
        onChanged();
      } else {
        iconBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public Builder clearIcon() {
      if (iconBuilder_ == null) {
        icon_ = null;
        onChanged();
      } else {
        icon_ = null;
        iconBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public app.schildpad.schildpad.protos.App.DrawableData.Builder getIconBuilder() {

      onChanged();
      return getIconFieldBuilder().getBuilder();
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    public app.schildpad.schildpad.protos.App.DrawableDataOrBuilder getIconOrBuilder() {
      if (iconBuilder_ != null) {
        return iconBuilder_.getMessageOrBuilder();
      } else {
        return icon_ == null ?
                app.schildpad.schildpad.protos.App.DrawableData.getDefaultInstance() : icon_;
      }
    }

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            app.schildpad.schildpad.protos.App.DrawableData, app.schildpad.schildpad.protos.App.DrawableData.Builder, app.schildpad.schildpad.protos.App.DrawableDataOrBuilder>
    getIconFieldBuilder() {
      if (iconBuilder_ == null) {
        iconBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                app.schildpad.schildpad.protos.App.DrawableData, app.schildpad.schildpad.protos.App.DrawableData.Builder, app.schildpad.schildpad.protos.App.DrawableDataOrBuilder>(
                getIcon(),
                getParentForChildren(),
                isClean());
        icon_ = null;
      }
      return iconBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:schildpad.App)
  }

  // @@protoc_insertion_point(class_scope:schildpad.App)
  private static final app.schildpad.schildpad.protos.App DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new app.schildpad.schildpad.protos.App();
  }

  public static app.schildpad.schildpad.protos.App getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<App>
          PARSER = new com.google.protobuf.AbstractParser<App>() {
    @java.lang.Override
    public App parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new App(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<App> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<App> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public app.schildpad.schildpad.protos.App getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

