// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_apps/proto/installed_apps.proto

package app.schildpad.schildpad.protos;

public interface AppOrBuilder extends
        // @@protoc_insertion_point(interface_extends:schildpad.App)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>string packageName = 2;</code>
     *
     * @return The packageName.
     */
    java.lang.String getPackageName();

    /**
     * <code>string packageName = 2;</code>
     *
     * @return The bytes for packageName.
     */
    com.google.protobuf.ByteString
    getPackageNameBytes();

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     *
     * @return Whether the icon field is set.
     */
    boolean hasIcon();

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     *
     * @return The icon.
     */
    app.schildpad.schildpad.protos.App.DrawableData getIcon();

    /**
     * <code>.schildpad.App.DrawableData icon = 3;</code>
     */
    app.schildpad.schildpad.protos.App.DrawableDataOrBuilder getIconOrBuilder();

    /**
     * <code>string launchComponent = 4;</code>
     *
     * @return The launchComponent.
     */
    java.lang.String getLaunchComponent();

    /**
     * <code>string launchComponent = 4;</code>
     *
     * @return The bytes for launchComponent.
     */
    com.google.protobuf.ByteString
    getLaunchComponentBytes();
}
