// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_app_widgets/proto/installed_app_widgets.proto

package app.schildpad.schildpad.protos;

public interface AppWidgetOrBuilder extends
        // @@protoc_insertion_point(interface_extends:schildpad.AppWidget)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string packageName = 1;</code>
     *
     * @return The packageName.
     */
    java.lang.String getPackageName();

    /**
     * <code>string packageName = 1;</code>
     *
     * @return The bytes for packageName.
     */
    com.google.protobuf.ByteString
    getPackageNameBytes();

    /**
     * <code>string componentName = 2;</code>
     *
     * @return The componentName.
     */
    java.lang.String getComponentName();

    /**
     * <code>string componentName = 2;</code>
     *
     * @return The bytes for componentName.
     */
    com.google.protobuf.ByteString
    getComponentNameBytes();

    /**
     * <code>string appName = 3;</code>
     *
     * @return The appName.
     */
    java.lang.String getAppName();

    /**
     * <code>string appName = 3;</code>
     *
     * @return The bytes for appName.
     */
    com.google.protobuf.ByteString
    getAppNameBytes();

    /**
     * <code>string label = 4;</code>
     *
     * @return The label.
     */
    java.lang.String getLabel();

    /**
     * <code>string label = 4;</code>
     *
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
    getLabelBytes();

    /**
     * <code>string description = 5;</code>
     *
     * @return The description.
     */
    java.lang.String getDescription();

    /**
     * <code>string description = 5;</code>
     *
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
    getDescriptionBytes();

    /**
     * <code>.schildpad.AppWidget.DrawableData icon = 6;</code>
     *
     * @return Whether the icon field is set.
     */
    boolean hasIcon();

    /**
     * <code>.schildpad.AppWidget.DrawableData icon = 6;</code>
     *
     * @return The icon.
     */
    app.schildpad.schildpad.protos.AppWidget.DrawableData getIcon();

    /**
     * <code>.schildpad.AppWidget.DrawableData icon = 6;</code>
     */
    app.schildpad.schildpad.protos.AppWidget.DrawableDataOrBuilder getIconOrBuilder();

    /**
     * <code>.schildpad.AppWidget.DrawableData preview = 7;</code>
     *
     * @return Whether the preview field is set.
     */
    boolean hasPreview();

    /**
     * <code>.schildpad.AppWidget.DrawableData preview = 7;</code>
     *
     * @return The preview.
     */
    app.schildpad.schildpad.protos.AppWidget.DrawableData getPreview();

    /**
     * <code>.schildpad.AppWidget.DrawableData preview = 7;</code>
     */
    app.schildpad.schildpad.protos.AppWidget.DrawableDataOrBuilder getPreviewOrBuilder();

    /**
     * <code>int32 targetWidth = 8;</code>
     *
     * @return The targetWidth.
     */
    int getTargetWidth();

    /**
     * <code>int32 targetHeight = 9;</code>
     *
     * @return The targetHeight.
     */
    int getTargetHeight();

    /**
     * <code>int32 minWidth = 10;</code>
     *
     * @return The minWidth.
     */
    int getMinWidth();

    /**
     * <code>int32 minHeight = 11;</code>
     *
     * @return The minHeight.
     */
    int getMinHeight();
}
