// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_app_widgets/proto/installed_app_widgets.proto

package app.schildpad.schildpad.protos;

/**
 * Protobuf type {@code schildpad.InstalledAppWidgets}
 */
public final class InstalledAppWidgets extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:schildpad.InstalledAppWidgets)
        InstalledAppWidgetsOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use InstalledAppWidgets.newBuilder() to construct.
    private InstalledAppWidgets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private InstalledAppWidgets() {
        appWidgets_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new InstalledAppWidgets();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private InstalledAppWidgets(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            appWidgets_ = new java.util.ArrayList<app.schildpad.schildpad.protos.AppWidget>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        appWidgets_.add(
                                input.readMessage(app.schildpad.schildpad.protos.AppWidget.parser(), extensionRegistry));
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                appWidgets_ = java.util.Collections.unmodifiableList(appWidgets_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return app.schildpad.schildpad.protos.InstalledAppWidgetsProtos.internal_static_schildpad_InstalledAppWidgets_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return app.schildpad.schildpad.protos.InstalledAppWidgetsProtos.internal_static_schildpad_InstalledAppWidgets_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        app.schildpad.schildpad.protos.InstalledAppWidgets.class, app.schildpad.schildpad.protos.InstalledAppWidgets.Builder.class);
    }

    public static final int APPWIDGETS_FIELD_NUMBER = 1;
    private java.util.List<app.schildpad.schildpad.protos.AppWidget> appWidgets_;

    /**
     * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<app.schildpad.schildpad.protos.AppWidget> getAppWidgetsList() {
        return appWidgets_;
    }

    /**
     * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends app.schildpad.schildpad.protos.AppWidgetOrBuilder>
    getAppWidgetsOrBuilderList() {
        return appWidgets_;
    }

    /**
     * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
     */
    @java.lang.Override
    public int getAppWidgetsCount() {
        return appWidgets_.size();
    }

    /**
     * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
     */
    @java.lang.Override
    public app.schildpad.schildpad.protos.AppWidget getAppWidgets(int index) {
        return appWidgets_.get(index);
    }

    /**
     * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
     */
    @java.lang.Override
    public app.schildpad.schildpad.protos.AppWidgetOrBuilder getAppWidgetsOrBuilder(
            int index) {
        return appWidgets_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < appWidgets_.size(); i++) {
            output.writeMessage(1, appWidgets_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < appWidgets_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, appWidgets_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof app.schildpad.schildpad.protos.InstalledAppWidgets)) {
            return super.equals(obj);
        }
        app.schildpad.schildpad.protos.InstalledAppWidgets other = (app.schildpad.schildpad.protos.InstalledAppWidgets) obj;

        if (!getAppWidgetsList()
                .equals(other.getAppWidgetsList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getAppWidgetsCount() > 0) {
            hash = (37 * hash) + APPWIDGETS_FIELD_NUMBER;
            hash = (53 * hash) + getAppWidgetsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(app.schildpad.schildpad.protos.InstalledAppWidgets prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code schildpad.InstalledAppWidgets}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:schildpad.InstalledAppWidgets)
            app.schildpad.schildpad.protos.InstalledAppWidgetsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return app.schildpad.schildpad.protos.InstalledAppWidgetsProtos.internal_static_schildpad_InstalledAppWidgets_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return app.schildpad.schildpad.protos.InstalledAppWidgetsProtos.internal_static_schildpad_InstalledAppWidgets_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            app.schildpad.schildpad.protos.InstalledAppWidgets.class, app.schildpad.schildpad.protos.InstalledAppWidgets.Builder.class);
        }

        // Construct using app.schildpad.schildpad.protos.InstalledAppWidgets.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getAppWidgetsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (appWidgetsBuilder_ == null) {
                appWidgets_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                appWidgetsBuilder_.clear();
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return app.schildpad.schildpad.protos.InstalledAppWidgetsProtos.internal_static_schildpad_InstalledAppWidgets_descriptor;
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledAppWidgets getDefaultInstanceForType() {
            return app.schildpad.schildpad.protos.InstalledAppWidgets.getDefaultInstance();
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledAppWidgets build() {
            app.schildpad.schildpad.protos.InstalledAppWidgets result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledAppWidgets buildPartial() {
            app.schildpad.schildpad.protos.InstalledAppWidgets result = new app.schildpad.schildpad.protos.InstalledAppWidgets(this);
            int from_bitField0_ = bitField0_;
            if (appWidgetsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    appWidgets_ = java.util.Collections.unmodifiableList(appWidgets_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.appWidgets_ = appWidgets_;
            } else {
                result.appWidgets_ = appWidgetsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof app.schildpad.schildpad.protos.InstalledAppWidgets) {
                return mergeFrom((app.schildpad.schildpad.protos.InstalledAppWidgets) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(app.schildpad.schildpad.protos.InstalledAppWidgets other) {
            if (other == app.schildpad.schildpad.protos.InstalledAppWidgets.getDefaultInstance()) return this;
            if (appWidgetsBuilder_ == null) {
                if (!other.appWidgets_.isEmpty()) {
                    if (appWidgets_.isEmpty()) {
                        appWidgets_ = other.appWidgets_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureAppWidgetsIsMutable();
                        appWidgets_.addAll(other.appWidgets_);
                    }
                    onChanged();
                }
            } else {
                if (!other.appWidgets_.isEmpty()) {
                    if (appWidgetsBuilder_.isEmpty()) {
                        appWidgetsBuilder_.dispose();
                        appWidgetsBuilder_ = null;
                        appWidgets_ = other.appWidgets_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        appWidgetsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getAppWidgetsFieldBuilder() : null;
                    } else {
                        appWidgetsBuilder_.addAllMessages(other.appWidgets_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            app.schildpad.schildpad.protos.InstalledAppWidgets parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (app.schildpad.schildpad.protos.InstalledAppWidgets) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<app.schildpad.schildpad.protos.AppWidget> appWidgets_ =
                java.util.Collections.emptyList();

        private void ensureAppWidgetsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                appWidgets_ = new java.util.ArrayList<app.schildpad.schildpad.protos.AppWidget>(appWidgets_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                app.schildpad.schildpad.protos.AppWidget, app.schildpad.schildpad.protos.AppWidget.Builder, app.schildpad.schildpad.protos.AppWidgetOrBuilder> appWidgetsBuilder_;

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public java.util.List<app.schildpad.schildpad.protos.AppWidget> getAppWidgetsList() {
            if (appWidgetsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(appWidgets_);
            } else {
                return appWidgetsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public int getAppWidgetsCount() {
            if (appWidgetsBuilder_ == null) {
                return appWidgets_.size();
            } else {
                return appWidgetsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppWidget getAppWidgets(int index) {
            if (appWidgetsBuilder_ == null) {
                return appWidgets_.get(index);
            } else {
                return appWidgetsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder setAppWidgets(
                int index, app.schildpad.schildpad.protos.AppWidget value) {
            if (appWidgetsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppWidgetsIsMutable();
                appWidgets_.set(index, value);
                onChanged();
            } else {
                appWidgetsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder setAppWidgets(
                int index, app.schildpad.schildpad.protos.AppWidget.Builder builderForValue) {
            if (appWidgetsBuilder_ == null) {
                ensureAppWidgetsIsMutable();
                appWidgets_.set(index, builderForValue.build());
                onChanged();
            } else {
                appWidgetsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder addAppWidgets(app.schildpad.schildpad.protos.AppWidget value) {
            if (appWidgetsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppWidgetsIsMutable();
                appWidgets_.add(value);
                onChanged();
            } else {
                appWidgetsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder addAppWidgets(
                int index, app.schildpad.schildpad.protos.AppWidget value) {
            if (appWidgetsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppWidgetsIsMutable();
                appWidgets_.add(index, value);
                onChanged();
            } else {
                appWidgetsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder addAppWidgets(
                app.schildpad.schildpad.protos.AppWidget.Builder builderForValue) {
            if (appWidgetsBuilder_ == null) {
                ensureAppWidgetsIsMutable();
                appWidgets_.add(builderForValue.build());
                onChanged();
            } else {
                appWidgetsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder addAppWidgets(
                int index, app.schildpad.schildpad.protos.AppWidget.Builder builderForValue) {
            if (appWidgetsBuilder_ == null) {
                ensureAppWidgetsIsMutable();
                appWidgets_.add(index, builderForValue.build());
                onChanged();
            } else {
                appWidgetsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder addAllAppWidgets(
                java.lang.Iterable<? extends app.schildpad.schildpad.protos.AppWidget> values) {
            if (appWidgetsBuilder_ == null) {
                ensureAppWidgetsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, appWidgets_);
                onChanged();
            } else {
                appWidgetsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder clearAppWidgets() {
            if (appWidgetsBuilder_ == null) {
                appWidgets_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                appWidgetsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public Builder removeAppWidgets(int index) {
            if (appWidgetsBuilder_ == null) {
                ensureAppWidgetsIsMutable();
                appWidgets_.remove(index);
                onChanged();
            } else {
                appWidgetsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppWidget.Builder getAppWidgetsBuilder(
                int index) {
            return getAppWidgetsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppWidgetOrBuilder getAppWidgetsOrBuilder(
                int index) {
            if (appWidgetsBuilder_ == null) {
                return appWidgets_.get(index);
            } else {
                return appWidgetsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public java.util.List<? extends app.schildpad.schildpad.protos.AppWidgetOrBuilder>
        getAppWidgetsOrBuilderList() {
            if (appWidgetsBuilder_ != null) {
                return appWidgetsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(appWidgets_);
            }
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppWidget.Builder addAppWidgetsBuilder() {
            return getAppWidgetsFieldBuilder().addBuilder(
                    app.schildpad.schildpad.protos.AppWidget.getDefaultInstance());
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppWidget.Builder addAppWidgetsBuilder(
                int index) {
            return getAppWidgetsFieldBuilder().addBuilder(
                    index, app.schildpad.schildpad.protos.AppWidget.getDefaultInstance());
        }

        /**
         * <code>repeated .schildpad.AppWidget appWidgets = 1;</code>
         */
        public java.util.List<app.schildpad.schildpad.protos.AppWidget.Builder>
        getAppWidgetsBuilderList() {
            return getAppWidgetsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                app.schildpad.schildpad.protos.AppWidget, app.schildpad.schildpad.protos.AppWidget.Builder, app.schildpad.schildpad.protos.AppWidgetOrBuilder>
        getAppWidgetsFieldBuilder() {
            if (appWidgetsBuilder_ == null) {
                appWidgetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        app.schildpad.schildpad.protos.AppWidget, app.schildpad.schildpad.protos.AppWidget.Builder, app.schildpad.schildpad.protos.AppWidgetOrBuilder>(
                        appWidgets_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                appWidgets_ = null;
            }
            return appWidgetsBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:schildpad.InstalledAppWidgets)
    }

    // @@protoc_insertion_point(class_scope:schildpad.InstalledAppWidgets)
    private static final app.schildpad.schildpad.protos.InstalledAppWidgets DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new app.schildpad.schildpad.protos.InstalledAppWidgets();
    }

    public static app.schildpad.schildpad.protos.InstalledAppWidgets getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstalledAppWidgets>
            PARSER = new com.google.protobuf.AbstractParser<InstalledAppWidgets>() {
        @java.lang.Override
        public InstalledAppWidgets parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new InstalledAppWidgets(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<InstalledAppWidgets> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstalledAppWidgets> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.InstalledAppWidgets getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

