// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_apps/proto/installed_apps.proto

package app.schildpad.schildpad.protos;

public interface InstalledAppsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:schildpad.InstalledApps)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    java.util.List<app.schildpad.schildpad.protos.App>
    getAppsList();

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    app.schildpad.schildpad.protos.App getApps(int index);

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    int getAppsCount();

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    java.util.List<? extends app.schildpad.schildpad.protos.AppOrBuilder>
    getAppsOrBuilderList();

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    app.schildpad.schildpad.protos.AppOrBuilder getAppsOrBuilder(
            int index);
}
