// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/installed_apps/proto/installed_apps.proto

package app.schildpad.schildpad.protos;

/**
 * Protobuf type {@code schildpad.InstalledApps}
 */
public final class InstalledApps extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:schildpad.InstalledApps)
        InstalledAppsOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use InstalledApps.newBuilder() to construct.
    private InstalledApps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private InstalledApps() {
        apps_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new InstalledApps();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private InstalledApps(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            apps_ = new java.util.ArrayList<app.schildpad.schildpad.protos.App>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        apps_.add(
                                input.readMessage(app.schildpad.schildpad.protos.App.parser(), extensionRegistry));
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                apps_ = java.util.Collections.unmodifiableList(apps_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_InstalledApps_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_InstalledApps_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        app.schildpad.schildpad.protos.InstalledApps.class, app.schildpad.schildpad.protos.InstalledApps.Builder.class);
    }

    public static final int APPS_FIELD_NUMBER = 1;
    private java.util.List<app.schildpad.schildpad.protos.App> apps_;

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    @java.lang.Override
    public java.util.List<app.schildpad.schildpad.protos.App> getAppsList() {
        return apps_;
    }

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends app.schildpad.schildpad.protos.AppOrBuilder>
    getAppsOrBuilderList() {
        return apps_;
    }

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    @java.lang.Override
    public int getAppsCount() {
        return apps_.size();
    }

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    @java.lang.Override
    public app.schildpad.schildpad.protos.App getApps(int index) {
        return apps_.get(index);
    }

    /**
     * <code>repeated .schildpad.App apps = 1;</code>
     */
    @java.lang.Override
    public app.schildpad.schildpad.protos.AppOrBuilder getAppsOrBuilder(
            int index) {
        return apps_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < apps_.size(); i++) {
            output.writeMessage(1, apps_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < apps_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, apps_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof app.schildpad.schildpad.protos.InstalledApps)) {
            return super.equals(obj);
        }
        app.schildpad.schildpad.protos.InstalledApps other = (app.schildpad.schildpad.protos.InstalledApps) obj;

        if (!getAppsList()
                .equals(other.getAppsList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getAppsCount() > 0) {
            hash = (37 * hash) + APPS_FIELD_NUMBER;
            hash = (53 * hash) + getAppsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static app.schildpad.schildpad.protos.InstalledApps parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(app.schildpad.schildpad.protos.InstalledApps prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code schildpad.InstalledApps}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:schildpad.InstalledApps)
            app.schildpad.schildpad.protos.InstalledAppsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_InstalledApps_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_InstalledApps_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            app.schildpad.schildpad.protos.InstalledApps.class, app.schildpad.schildpad.protos.InstalledApps.Builder.class);
        }

        // Construct using app.schildpad.schildpad.protos.InstalledApps.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getAppsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (appsBuilder_ == null) {
                apps_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                appsBuilder_.clear();
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return app.schildpad.schildpad.protos.InstalledAppsProtos.internal_static_schildpad_InstalledApps_descriptor;
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledApps getDefaultInstanceForType() {
            return app.schildpad.schildpad.protos.InstalledApps.getDefaultInstance();
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledApps build() {
            app.schildpad.schildpad.protos.InstalledApps result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public app.schildpad.schildpad.protos.InstalledApps buildPartial() {
            app.schildpad.schildpad.protos.InstalledApps result = new app.schildpad.schildpad.protos.InstalledApps(this);
            int from_bitField0_ = bitField0_;
            if (appsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    apps_ = java.util.Collections.unmodifiableList(apps_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.apps_ = apps_;
            } else {
                result.apps_ = appsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof app.schildpad.schildpad.protos.InstalledApps) {
                return mergeFrom((app.schildpad.schildpad.protos.InstalledApps) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(app.schildpad.schildpad.protos.InstalledApps other) {
            if (other == app.schildpad.schildpad.protos.InstalledApps.getDefaultInstance()) return this;
            if (appsBuilder_ == null) {
                if (!other.apps_.isEmpty()) {
                    if (apps_.isEmpty()) {
                        apps_ = other.apps_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureAppsIsMutable();
                        apps_.addAll(other.apps_);
                    }
                    onChanged();
                }
            } else {
                if (!other.apps_.isEmpty()) {
                    if (appsBuilder_.isEmpty()) {
                        appsBuilder_.dispose();
                        appsBuilder_ = null;
                        apps_ = other.apps_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        appsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getAppsFieldBuilder() : null;
                    } else {
                        appsBuilder_.addAllMessages(other.apps_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            app.schildpad.schildpad.protos.InstalledApps parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (app.schildpad.schildpad.protos.InstalledApps) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<app.schildpad.schildpad.protos.App> apps_ =
                java.util.Collections.emptyList();

        private void ensureAppsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                apps_ = new java.util.ArrayList<app.schildpad.schildpad.protos.App>(apps_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                app.schildpad.schildpad.protos.App, app.schildpad.schildpad.protos.App.Builder, app.schildpad.schildpad.protos.AppOrBuilder> appsBuilder_;

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public java.util.List<app.schildpad.schildpad.protos.App> getAppsList() {
            if (appsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(apps_);
            } else {
                return appsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public int getAppsCount() {
            if (appsBuilder_ == null) {
                return apps_.size();
            } else {
                return appsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public app.schildpad.schildpad.protos.App getApps(int index) {
            if (appsBuilder_ == null) {
                return apps_.get(index);
            } else {
                return appsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder setApps(
                int index, app.schildpad.schildpad.protos.App value) {
            if (appsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppsIsMutable();
                apps_.set(index, value);
                onChanged();
            } else {
                appsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder setApps(
                int index, app.schildpad.schildpad.protos.App.Builder builderForValue) {
            if (appsBuilder_ == null) {
                ensureAppsIsMutable();
                apps_.set(index, builderForValue.build());
                onChanged();
            } else {
                appsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder addApps(app.schildpad.schildpad.protos.App value) {
            if (appsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppsIsMutable();
                apps_.add(value);
                onChanged();
            } else {
                appsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder addApps(
                int index, app.schildpad.schildpad.protos.App value) {
            if (appsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAppsIsMutable();
                apps_.add(index, value);
                onChanged();
            } else {
                appsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder addApps(
                app.schildpad.schildpad.protos.App.Builder builderForValue) {
            if (appsBuilder_ == null) {
                ensureAppsIsMutable();
                apps_.add(builderForValue.build());
                onChanged();
            } else {
                appsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder addApps(
                int index, app.schildpad.schildpad.protos.App.Builder builderForValue) {
            if (appsBuilder_ == null) {
                ensureAppsIsMutable();
                apps_.add(index, builderForValue.build());
                onChanged();
            } else {
                appsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder addAllApps(
                java.lang.Iterable<? extends app.schildpad.schildpad.protos.App> values) {
            if (appsBuilder_ == null) {
                ensureAppsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, apps_);
                onChanged();
            } else {
                appsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder clearApps() {
            if (appsBuilder_ == null) {
                apps_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                appsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public Builder removeApps(int index) {
            if (appsBuilder_ == null) {
                ensureAppsIsMutable();
                apps_.remove(index);
                onChanged();
            } else {
                appsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public app.schildpad.schildpad.protos.App.Builder getAppsBuilder(
                int index) {
            return getAppsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public app.schildpad.schildpad.protos.AppOrBuilder getAppsOrBuilder(
                int index) {
            if (appsBuilder_ == null) {
                return apps_.get(index);
            } else {
                return appsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public java.util.List<? extends app.schildpad.schildpad.protos.AppOrBuilder>
        getAppsOrBuilderList() {
            if (appsBuilder_ != null) {
                return appsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(apps_);
            }
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public app.schildpad.schildpad.protos.App.Builder addAppsBuilder() {
            return getAppsFieldBuilder().addBuilder(
                    app.schildpad.schildpad.protos.App.getDefaultInstance());
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public app.schildpad.schildpad.protos.App.Builder addAppsBuilder(
                int index) {
            return getAppsFieldBuilder().addBuilder(
                    index, app.schildpad.schildpad.protos.App.getDefaultInstance());
        }

        /**
         * <code>repeated .schildpad.App apps = 1;</code>
         */
        public java.util.List<app.schildpad.schildpad.protos.App.Builder>
        getAppsBuilderList() {
            return getAppsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                app.schildpad.schildpad.protos.App, app.schildpad.schildpad.protos.App.Builder, app.schildpad.schildpad.protos.AppOrBuilder>
        getAppsFieldBuilder() {
            if (appsBuilder_ == null) {
                appsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        app.schildpad.schildpad.protos.App, app.schildpad.schildpad.protos.App.Builder, app.schildpad.schildpad.protos.AppOrBuilder>(
                        apps_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                apps_ = null;
            }
            return appsBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:schildpad.InstalledApps)
    }

    // @@protoc_insertion_point(class_scope:schildpad.InstalledApps)
    private static final app.schildpad.schildpad.protos.InstalledApps DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new app.schildpad.schildpad.protos.InstalledApps();
    }

    public static app.schildpad.schildpad.protos.InstalledApps getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstalledApps>
            PARSER = new com.google.protobuf.AbstractParser<InstalledApps>() {
        @java.lang.Override
        public InstalledApps parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new InstalledApps(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<InstalledApps> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstalledApps> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public app.schildpad.schildpad.protos.InstalledApps getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

